version: '2'

services:

  tokamak-elasticsearch:
    build: '.'
    image: 'wrmsr/tokamak-elasticsearch:latest'
    restart: 'always'
    environment:
      ES_JAVA_OPTS: '-Xms750m -Xmx750m'
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
    expose:
      - '9200'
    ports:
      - '21211:9200'

  tokamak-kafka:
    image: 'wrmsr/tokamak-kafka:latest'
    hostname: 'tokamak-kafka'
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER_DOCKER_INTERNAL://tokamak-kafka:19092,LISTENER_DOCKER_EXTERNAL://127.0.0.1:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'LISTENER_DOCKER_INTERNAL'
      KAFKA_ZOOKEEPER_CONNECT: 'tokamak-zookeeper:2181'
      KAFKA_BROKER_ID: '1'
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - '../temp/kafka/data:/var/lib/kafka/data'
    depends_on:
      - 'tokamak-zookeeper'
    expose:
      - '9092'
    ports:
      - '21212:9092'

  tokamak-memcached:
    build: '.'
    image: 'wrmsr/tokamak-memcached:latest'
    restart: 'always'
    expose:
      - '11211'
    ports:
      - '21213:11211'

  tokamak-minio:
    build: '.'
    image: 'wrmsr/tokamak-minio:latest'
    restart: 'always'
    environment:
      MINIO_ACCESS_KEY: 'AKIAIOSFODNN7EXAMPLE'
      MINIO_SECRET_KEY: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
    expose:
      - '9000'
    ports:
      - '21214:9000'

  tokamak-mysql-master:
    build: '.'
    image: 'wrmsr/tokamak-mysql:latest'
    restart: 'always'
    environment:
      MYSQL_USER: 'tokamak'
      MYSQL_PASSWORD: 'tokamak'
      MYSQL_ROOT_PASSWORD: 'tokamak'
    expose:
      - '3306'
    ports:
      - '21215:3306'

  tokamak-mysql-slave:
    build: '.'
    image: 'wrmsr/tokamak-mysql:latest'
    restart: 'always'
    environment:
      MYSQL_USER: 'tokamak'
      MYSQL_PASSWORD: 'tokamak'
      MYSQL_ROOT_PASSWORD: 'tokamak'
      REPLICATE_FROM: 'tokamak-mysql-master'
    links:
      - 'tokamak-mysql-master'
    depends_on:
      - 'tokamak-mysql-master'
    expose:
      - '3306'
    ports:
      - '21216:3306'

  tokamak-postgres-master:
    build: '.'
    image: 'wrmsr/tokamak-postgres:latest'
    restart: 'always'
    environment:
      POSTGRES_USER: 'tokamak'
      POSTGRES_PASSWORD: 'tokamak'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    expose:
      - '5432'
    ports:
      - '21217:5432'

  tokamak-postgres-slave:
    build: '.'
    image: 'wrmsr/tokamak-postgres:latest'
    restart: 'always'
    environment:
      POSTGRES_USER: 'tokamak'
      POSTGRES_PASSWORD: 'tokamak'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      REPLICATE_FROM: 'tokamak-postgres-master'
    links:
      - 'tokamak-postgres-master'
    depends_on:
      - 'tokamak-postgres-master'
    expose:
      - '5432'
    ports:
      - '21218:5432'

  tokamak-redis:
    build: '.'
    image: 'wrmsr/tokamak-redis:latest'
    restart: 'always'
    expose:
      - '6379'
    ports:
      - '21219:6379'

  tokamak-zookeeper:
    image: 'wrmsr/tokamak-zookeeper:latest'
    hostname: 'tokamak-zookeeper'
    environment:
      ZOO_MY_ID: '1'
      ZOO_PORT: '2181'
      ZOO_SERVERS: 'server.1=tokamak-zookeeper:2888:3888'
    volumes:
      - '../temp/zookeeper/data:/data'
      - '../temp/zookeeper/datalog:/datalog'
    expose:
      - '2181'
    ports:
      - '21220:2181'

  tokamak-dev:
    build: '.'
    image: 'wrmsr/tokamak-dev:latest'
    restart: 'always'
    cap_add:
      - 'SYS_PTRACE'
    security_opt:
      - 'apparmor:unconfined'
    volumes:
      - '..:/tokamak'
    depends_on:
      - 'tokamak-elasticsearch'
      - 'tokamak-kafka'
      - 'tokamak-memcached'
      - 'tokamak-mysql-master'
      - 'tokamak-mysql-slave'
      - 'tokamak-postgres-master'
      - 'tokamak-postgres-slave'
      - 'tokamak-redis'
      - 'tokamak-zookeeper'
    links:
      - 'tokamak-elasticsearch'
      - 'tokamak-kafka'
      - 'tokamak-memcached'
      - 'tokamak-mysql-master'
      - 'tokamak-mysql-slave'
      - 'tokamak-postgres-master'
      - 'tokamak-postgres-slave'
      - 'tokamak-redis'
      - 'tokamak-zookeeper'
    expose:
      - '8000'
    ports:
      - '21210:8000'
